### ISSUE TITLE
Cannot see any video.

### ISSUE THREAD

**Issue by mlopezgva** [NeeRaj-2401/ReacTube#5]
Hi!

I've tried the "demo" page.
Whenever I select a video to watch, I only get a white line (a box, with 2px height, in fact) and no video.

I looked into the Inspector, and I saw this:

	Request URL:		https://pipedapi.kavin.rocks/streams/AAq06bS8UZM
	Request Method:	GET
	Status Code:		500 Internal Server Error (from service worker)
	Referrer Policy:	strict-origin-when-cross-origin

```json
{
    "error": "	org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: 'Sign in to confirm that you're not a bot'
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.checkPlayabilityStatus(YoutubeStreamExtractor.java:898)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:784)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:67)
	at me.kavin.piped.server.handlers.StreamHandlers.lambda$streamsResponse$0(StreamHandlers.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
",
    "message": "Got error: \"Sign in to confirm that you're not a bot\""
}
```
Is that something expected? Thank you.

**Comment by NeeRaj-2401** [comment]
Hello, Thank you for using Reactube, as it totally depends on [Piped API](https://github.com/TeamPiped/Piped), to get proxied video url (to achieve privacy) from public instances of piped apis, and due to recent changes by YouTube, Piped is currently facing the same issues as noted in https://github.com/TeamPiped/Piped/issues/3658 , 

I may need to wait for Piped to resolve this or consider alternative methods to achieve the same functionality. I’ll definitely look into it and find a solution. Thank you.
